### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by silveltman** [dc7290/astro-fonts-next#29]
Getting the following error:

`ENOENT: no such file or directory, open '\C:\Users\silve\Documents\Web%20dev\astro\astro-webtunus\node_modules\astro-fonts-next\dist\urls.json'`

**Comment by dc7290** [comment]
@silveltman 

Thank you for issuing the issue.
Can you provide a reproducible repository so we can review the issue?

**Comment by antonkristiono** [comment]
error   ENOENT: no such file or directory, open '\C:\Users\anton\Code\dev\astro-ulem\node_modules\.pnpm\astro-fonts-next@1.0.2_astro@1.0.0-beta.72\node_modules\astro-fonts-next\dist\urls.json'
    at Object.openSync (node:fs:585:3)
    at writeFileSync (node:fs:2170:35)
    at Object.astro:config:setup (file:///C:/Users/anton/Code/dev/astro-ulem/node_modules/.pnpm/astro-fonts-next@1.0.2_astro@1.0.0-beta.72/node_modules/astro-fonts-next/dist/index.js:52:21)
    at Object.openSync (node:fs:585:3)
    at writeFileSync (node:fs:2170:35)
    at Object.astro:config:setup (file:///C:/Users/anton/Code/dev/astro-ulem/node_modules/.pnpm/astro-fonts-next@1.0.2_astro@1.0.0-beta.72/node_modules/astro-fonts-next/dist/index.js:52:21)
    at runHookConfigSetup (file:///C:/Users/anton/Code/dev/astro-ulem/node_modules/.pnpm/astro@1.0.0-beta.72/node_modules/astro/dist/integrations/index.js:41:52)
    at async dev (file:///C:/Users/anton/Code/dev/astro-ulem/node_modules/.pnpm/astro@1.0.0-beta.72/node_modules/astro/dist/core/dev/index.js:19:12)
    at async runCommand (file:///C:/Users/anton/Code/dev/astro-ulem/node_modules/.pnpm/astro@1.0.0-beta.72/node_modules/astro/dist/cli/index.js:105:7)
    at async cli (file:///C:/Users/anton/Code/dev/astro-ulem/node_modules/.pnpm/astro@1.0.0-beta.72/node_modules/astro/dist/cli/index.js:127:5)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by antonkristiono** [comment]
error   ENOENT: no such file or directory, open '\C:\Users\anton\Code\dev\astro-ulem\node_modules\.pnpm\astro-fonts-next@1.0.2_astro@1.0.0-beta.72\node_modules\astro-fonts-next\dist\urls.json'
 
    at Object.openSync (node:fs:585:3)
    at writeFileSync (node:fs:2170:35)
    at Object.astro:config:setup (file:///C:/Users/anton/Code/dev/astro-ulem/node_modules/.pnpm/astro-fonts-next@1.0.2_astro@1.0.0-beta.72/node_modules/astro-fonts-next/dist/index.js:52:21)
    at Object.openSync (node:fs:585:3)
    at writeFileSync (node:fs:2170:35)
    at Object.astro:config:setup (file:///C:/Users/anton/Code/dev/astro-ulem/node_modules/.pnpm/astro-fonts-next@1.0.2_astro@1.0.0-beta.72/node_modules/astro-fonts-next/dist/index.js:52:21)
    at runHookConfigSetup (file:///C:/Users/anton/Code/dev/astro-ulem/node_modules/.pnpm/astro@1.0.0-beta.72/node_modules/astro/dist/integrations/index.js:41:52)
    at async dev (file:///C:/Users/anton/Code/dev/astro-ulem/node_modules/.pnpm/astro@1.0.0-beta.72/node_modules/astro/dist/core/dev/index.js:19:12)
    at async runCommand (file:///C:/Users/anton/Code/dev/astro-ulem/node_modules/.pnpm/astro@1.0.0-beta.72/node_modules/astro/dist/cli/index.js:105:7)
    at async cli (file:///C:/Users/anton/Code/dev/astro-ulem/node_modules/.pnpm/astro@1.0.0-beta.72/node_modules/astro/dist/cli/index.js:127:5)
    
 ELIFECYCLE  Command failed with exit code 1.

**Comment by dc7290** [comment]
When creating dirname, the method was not cross-platform compatible, so it has been corrected.

**Comment by dc7290** [comment]
🎉 This issue is included in version v1.0.3.

**Comment by antonkristiono** [comment]
Arigatou
